### ISSUE TITLE
[BUG] - Crashes to home screen.

### ISSUE THREAD

**Issue by hamishm456** [damontecres/StashAppAndroidTV#160]
### Description

Newly installed, unable to play any scenes.
Connects successfully to stash server. Both the server and client are latest versions.
I select a scene to play and it goes back to home screen. Have tried tips and tricks no luck.

### Reproduction steps

```bash
1. Click on 'any scene'
2. Returns to home screen with no errors.
```

### Device

Android Firestick 4k

**Comment by hamishm456** [comment]
Uninstalled then redownloaded/installed app (version code 16)
Unfortunately for same result.
Fire OS version is 7.6.6.9

**Comment by damontecres** [comment]
Hi @hamishm456, fixes are available only after a release occurs.

I just released [`v0.1.6`](https://github.com/damontecres/StashAppAndroidTV/releases/tag/v0.1.6) a few minuted ago. It contains #161 which I believe will fix your crash.

You can install it on top of your existing version too! Please let me know if the crash is fixed for you now!

**Comment by hamishm456** [comment]
@damontecres sorry my mad. 
Installed again and its now working
Thankyou very much, great work

**Comment by fazilps** [comment]
I'm facing a similar issue of crashing back to home screen without any error message. Been facing this issue since version 0.3 and all subsequent releases.

Device: NVIDIA Shield Pro
App Version: 0.3.2

I performed a reinstall of the app after deleting the app's cache and data. I tried with both PIN and no PIN.

`1. Open app
2. Enter PIN
3. Logs into home screen
4. Return to home screen with no error message.
5. However, if there is an app update available, the "update available" notification appears just before crashing to home screen`

**Comment by fazilps** [comment]
@damontecres Sorry I missed providing that info earlier. I have been running the latest server version as well.

Server version: v0.26.2
Host: Windows 11 23H2 with all latest updates
Client: Nvidia Shield TV Pro on latest update Android 11, SW Version 9.1.1

**Comment by fazilps** [comment]
Could the library size or something related be the issue? I am slowly migrating from Plex to stash. It might be that once I added more content that the app started crashing. 
The current library size is around 26K scenes, 10K images. Around 35TB of source materials. :)
