### ISSUE TITLE
[FEA] - Filter button on the performer/studio page

### ISSUE THREAD

**Issue by devstash** [damontecres/StashAppAndroidTV#178]
### Description

First of all: Thank you for this great software. It really makes using Stash a lot more useful.

What I'm missing a little is a filter button on the performer/studio page, similar to the WebUI. The WebUI allows selecting predefined filters here as well.

As an addition, it would also be nice to reach the filter menu by pressing the menu button (☰) on the remote. (Instead of scrolling up though all the scenes).

**Comment by damontecres** [comment]
Hey, thanks for the feedback!

> it would also be nice to reach the filter menu by pressing the menu button (☰) on the remote

I can look into this. Not all remotes have this button and on my NVIDIA shield this button is mapped to something else entirely. But maybe a settings to toggle this functionality would be good.

But, you should be able to navigate right on the grid to the right-most item, then right again to move to the `Filters` button so at least you don't need to scroll all the way up.

> filter button on the performer/studio page, similar to the WebUI

I think you mean the button to filter by whatever you want instead of only a saved filter? I agree that this would be nice to have, but there are couple challenges with this.

There are so many options (over 30 just for performers!) and most of them would be difficult (or at the very least, awkward) to input on a TV interface.

And to my knowledge, the full list of filter-able properties isn't available programmatically. The [web UI uses a static typescript list](https://github.com/stashapp/stash/blob/v0.24.3/ui/v2.5/src/models/list-filter/performers.ts#L80), so the Android TV app would have hardcode them as well.

So, it would be great to have, but probably won't happen for a while.
