### ISSUE TITLE
[BUG] - Can't get rid of progress bar

### ISSUE THREAD

**Issue by argash** [damontecres/StashAppAndroidTV#18]
### Description

When playing a scene if you skip forward the progress bar will stay on the screen after you resume playing the video. Additionally this keeps the brightness of the video dim.

### Reproduction steps

```bash
1. Click on scene
2. Skip forward for a bit
3. Note that the progress bar never goes away. if you try the back triangle it just returns to the beginning of the scene
```

### Device

NVIDIA Shield Pro

**Comment by damontecres** [comment]
Assuming you are using the right D-pad button to skip forward, you should be able to press enter or play/pause on the remote after skipping forward and the video will resume from the selected position.

Using the UI fast-forward button (ie, press enter then up/right to the FF button) also works. 

Finally, using the remote's FF/rewind buttons don't work either.

I'm not sure why the behavior is different for all of these, but it's on my list to invesigate.

**Comment by argash** [comment]
Yes I am using right on the shield D-pad then pressing play. The progress bar never goes away. I can get a video of it for you if you need to see it.

**Comment by argash** [comment]
Tried it again and yes if you use the center button the resume play it does go away. So I guess the bug is related to using the play/pause button.

**Comment by damontecres** [comment]
It seems that seeking using the built in progress/seek bar intentionally pauses. I tried some workarounds without success.

One thing that did work was to just always play the video after a seek. But if you pause then seek, the video would play instead of staying paused which isn't great UX.

I think ultimately fixing this might require a custom implementation of the seek bar instead of trying to workaround Android's built in one.
